#!/bin/sh

startclient() {
    Xorg &
    openbox &
    if [ -e /app/start.sh ]; then
        source /app/start.sh &
    else
        xterm &
    fi
}
start() {
        printf "start client"
        export DISPLAY=:0.0 
        export LANG=zh_CN.UTF-8
        startclient &
        echo "start client OK"
}
stop() {
        echo "start client OK"
}
restart() {
        echo "start client OK"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
